"""Pytest fixtures for Jarvis Tools tests.

Provides mock PostgreSQL + pgvector infrastructure via InMemoryDB, allowing
tests to run without a real database. The MockPool/MockCursor translate SQL
patterns generated by production code into in-memory dict operations.

Supports two logical tables (dual-compatible with old/new schema names):
- local.memories (was core.memories): observations, patterns, learnings, etc.
- obsidian.documents (was vault.documents): indexed vault file chunks
- local.meta (was core.meta): key-value metadata store
"""

import hashlib
import json
import math
import os
import re
import tempfile
from collections import Counter
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Generator
from unittest.mock import MagicMock

import pytest


# ── Mock Embedding Service ─────────────────────────────────────────────


class MockEmbeddingService:
    """Returns deterministic 384d vectors based on text content hash.

    Similar texts produce similar vectors (via SHA-256 hash),
    enabling realistic vector search in tests.
    """

    def __init__(self, dimensions=384):
        self._dimensions = dimensions

    def encode(self, text: str) -> list[float]:
        h = hashlib.sha256(text.encode()).digest()
        vec = [(h[i % len(h)] / 255.0) * 2 - 1 for i in range(self._dimensions)]
        norm = math.sqrt(sum(x * x for x in vec))
        return [x / norm for x in vec] if norm > 0 else vec

    def encode_batch(self, texts: list[str], batch_size: int = 64) -> list[list[float]]:
        return [self.encode(t) for t in texts]

    @property
    def dimensions(self) -> int:
        return self._dimensions

    @property
    def model_name(self) -> str:
        return "mock-model"

    @property
    def backend(self) -> str:
        return "mock"

    @property
    def is_loaded(self) -> bool:
        return True


# ── In-memory PostgreSQL mock ──────────────────────────────────────────


def _cosine_distance(a, b):
    """Cosine distance: 0 = identical, 2 = opposite."""
    if not a or not b:
        return 1.0
    min_len = min(len(a), len(b))
    a, b = a[:min_len], b[:min_len]
    dot = sum(x * y for x, y in zip(a, b))
    norm_a = math.sqrt(sum(x * x for x in a))
    norm_b = math.sqrt(sum(x * x for x in b))
    if norm_a == 0 or norm_b == 0:
        return 1.0
    return max(0.0, 1.0 - (dot / (norm_a * norm_b)))


# Core memory columns (everything that's NOT in JSONB metadata)
_CORE_COLUMNS = frozenset({
    "id", "document", "embedding", "category", "scope", "project",
    "source", "importance_score", "retrieval_count", "status",
    "superseded_by", "deleted_at", "metadata", "created_at", "updated_at",
})

# Vault document columns
_VAULT_COLUMNS = frozenset({
    "id", "document", "embedding", "parent_file", "directory",
    "vault_type", "title", "chunk_index", "chunk_total",
    "chunk_heading", "importance_score", "metadata",
    "created_at", "updated_at",
})


class InMemoryDB:
    """In-memory mock for the dual-schema PostgreSQL architecture.

    Stores documents in two logical tables:
    - core_rows: local.memories (observations, patterns, strategic, etc.)
    - vault_rows: obsidian.documents (indexed vault file chunks)
    - meta_rows: local.meta (key-value metadata)

    Each row is a flat dict with columns at the top level plus a 'metadata'
    key for the remaining JSONB.
    """

    def __init__(self):
        self.core_rows = {}   # id -> row dict (local.memories)
        self.vault_rows = {}  # id -> row dict (obsidian.documents)
        self.meta_rows = {}   # key -> {key, value, updated_at}
        # Backward compat alias — some tests may reference db.rows
        self.rows = self.core_rows

    def upsert_core(self, row_id, document, embedding, category="observation",
                    scope="global", project=None, source="auto-extract",
                    importance_score=0.5, retrieval_count=0.0,
                    metadata=None, created_at=None, updated_at=None):
        """Insert/update a row in core.memories."""
        now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        if isinstance(metadata, str):
            metadata = json.loads(metadata)
        metadata = dict(metadata) if metadata else {}

        existing = self.core_rows.get(row_id)
        self.core_rows[row_id] = {
            "id": row_id,
            "document": document,
            "embedding": embedding if isinstance(embedding, list) else list(embedding or []),
            "category": category,
            "scope": scope,
            "project": project,
            "source": source,
            "importance_score": float(importance_score),
            "retrieval_count": float(retrieval_count),
            "status": existing["status"] if existing else "active",
            "superseded_by": existing.get("superseded_by") if existing else None,
            "deleted_at": existing.get("deleted_at") if existing else None,
            "metadata": metadata,
            "created_at": created_at or (existing["created_at"] if existing else now),
            "updated_at": updated_at or now,
        }

    def upsert_vault(self, row_id, document, embedding, parent_file="",
                     directory="", vault_type="document", title="",
                     chunk_index=0, chunk_total=1, chunk_heading="",
                     importance_score=0.5, metadata=None,
                     created_at=None, updated_at=None):
        """Insert/update a row in vault.documents."""
        now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        if isinstance(metadata, str):
            metadata = json.loads(metadata)
        metadata = dict(metadata) if metadata else {}

        existing = self.vault_rows.get(row_id)
        self.vault_rows[row_id] = {
            "id": row_id,
            "document": document,
            "embedding": embedding if isinstance(embedding, list) else list(embedding or []),
            "parent_file": parent_file,
            "directory": directory,
            "vault_type": vault_type,
            "title": title,
            "chunk_index": int(chunk_index),
            "chunk_total": int(chunk_total),
            "chunk_heading": chunk_heading,
            "importance_score": float(importance_score),
            "metadata": metadata,
            "created_at": created_at or (existing["created_at"] if existing else now),
            "updated_at": updated_at or now,
        }

    # Legacy compatibility: upsert() routes to core by default
    def upsert(self, row_id, document, embedding, metadata_json,
               created_at=None, updated_at=None):
        """Legacy upsert — routes to core.memories for backward compat."""
        if isinstance(metadata_json, str):
            meta = json.loads(metadata_json)
        elif isinstance(metadata_json, dict):
            meta = dict(metadata_json)
        else:
            meta = {}

        # Extract columns from metadata for core table
        category = meta.pop("category", meta.pop("type", "observation"))
        if hasattr(category, "value"):
            category = category.value
        scope = meta.pop("scope", "global")
        project = meta.pop("project", None)
        source = meta.pop("source", "auto-extract")
        importance = float(meta.pop("importance_score",
                                    meta.pop("importance", 0.5)))
        retrieval_count = float(meta.pop("retrieval_count", 0.0))

        self.upsert_core(
            row_id, document, embedding,
            category=category, scope=scope, project=project,
            source=source, importance_score=importance,
            retrieval_count=retrieval_count, metadata=meta,
            created_at=created_at, updated_at=updated_at,
        )

    def get_core(self, row_id):
        row = self.core_rows.get(row_id)
        return dict(row) if row else None

    def get_vault(self, row_id):
        row = self.vault_rows.get(row_id)
        return dict(row) if row else None

    def get(self, row_id):
        """Get from either table."""
        return self.get_core(row_id) or self.get_vault(row_id)

    def get_many_core(self, ids):
        return [dict(self.core_rows[rid]) for rid in ids if rid in self.core_rows]

    def get_many_vault(self, ids):
        return [dict(self.vault_rows[rid]) for rid in ids if rid in self.vault_rows]

    def delete_core(self, row_id):
        return self.core_rows.pop(row_id, None) is not None

    def delete_vault(self, row_id):
        return self.vault_rows.pop(row_id, None) is not None

    def delete(self, row_id):
        return self.delete_core(row_id) or self.delete_vault(row_id)

    def delete_vault_where(self, key, value):
        """Delete vault rows where a column matches a value."""
        to_delete = [
            rid for rid, row in self.vault_rows.items()
            if row.get(key) == value
        ]
        for rid in to_delete:
            del self.vault_rows[rid]
        return len(to_delete)

    def _filter_rows(self, store, conditions=None, active_only=False):
        """Filter rows from a store with column-based conditions.

        Keys prefixed with '_meta_' are resolved from row['metadata'] sub-dict
        (e.g., '_meta_session_id' looks up row['metadata']['session_id']).
        """
        rows = list(store.values())
        if active_only:
            rows = [r for r in rows if r.get("status") == "active"]
        if not conditions:
            return rows
        for key, op, value in conditions:
            # Resolve _meta_ prefixed keys from metadata sub-dict
            if key.startswith("_meta_"):
                meta_key = key[6:]  # strip '_meta_' prefix
                def _get_val(r, mk=meta_key):
                    return r.get("metadata", {}).get(mk, "")
            else:
                def _get_val(r, k=key):
                    return r.get(k, "")

            if op == "=":
                val_cmp = value if isinstance(value, str) else str(value)
                rows = [r for r in rows if str(_get_val(r)) == val_cmp]
            elif op == ">=":
                try:
                    fval = float(value)
                    rows = [r for r in rows if float(_get_val(r) or 0) >= fval]
                except (ValueError, TypeError):
                    pass
            elif op == "LIKE":
                pattern = re.escape(str(value)).replace(r"\%", ".*")
                rows = [
                    r for r in rows
                    if re.search(pattern, str(_get_val(r)))
                ]
        return rows

    def list_core(self, conditions=None, order_by=None, limit=None, active_only=False):
        rows = [dict(r) for r in self._filter_rows(self.core_rows, conditions, active_only)]
        if order_by:
            field, direction = order_by
            reverse = direction == "DESC"
            def sort_key(r):
                val = r.get(field)
                if field in ("created_at", "updated_at"):
                    return val or ""
                try:
                    return float(val) if val is not None else 0.0
                except (ValueError, TypeError):
                    return 0.0
            try:
                rows.sort(key=sort_key, reverse=reverse)
            except (ValueError, TypeError):
                pass
        if limit:
            rows = rows[:limit]
        return rows

    def list_vault(self, conditions=None, order_by=None, limit=None):
        rows = [dict(r) for r in self._filter_rows(self.vault_rows, conditions)]
        if order_by:
            field, direction = order_by
            reverse = direction == "DESC"
            def sort_key(r):
                val = r.get(field)
                if field in ("created_at", "updated_at"):
                    return val or ""
                try:
                    return float(val) if val is not None else 0.0
                except (ValueError, TypeError):
                    return 0.0
            try:
                rows.sort(key=sort_key, reverse=reverse)
            except (ValueError, TypeError):
                pass
        if limit:
            rows = rows[:limit]
        return rows

    def vector_search_core(self, query_embedding, limit, conditions=None, active_only=False):
        rows = [dict(r) for r in self._filter_rows(self.core_rows, conditions, active_only)]
        for r in rows:
            r["distance"] = _cosine_distance(query_embedding, r.get("embedding", []))
        rows.sort(key=lambda r: r["distance"])
        return rows[:limit]

    def vector_search_vault(self, query_embedding, limit, conditions=None):
        rows = [dict(r) for r in self._filter_rows(self.vault_rows, conditions)]
        for r in rows:
            r["distance"] = _cosine_distance(query_embedding, r.get("embedding", []))
        rows.sort(key=lambda r: r["distance"])
        return rows[:limit]

    # Legacy methods for backward compat
    def count(self, conditions=None):
        return len(self._filter_rows(self.core_rows, conditions))

    def vector_search(self, query_embedding, limit, conditions=None):
        return self.vector_search_core(query_embedding, limit, conditions)

    def list_filtered(self, conditions=None, order_by=None, limit=None):
        return self.list_core(conditions, order_by, limit)

    def delete_where_metadata(self, key, value):
        """Legacy: delete core rows where metadata[key] == value."""
        to_delete = [
            rid for rid, row in self.core_rows.items()
            if row["metadata"].get(key) == value
        ]
        for rid in to_delete:
            del self.core_rows[rid]
        return len(to_delete)

    def clear(self):
        self.core_rows.clear()
        self.vault_rows.clear()
        self.meta_rows.clear()


# ── Mock psycopg cursor / connection / pool ────────────────────────────


class _Col:
    """Minimal column descriptor for cursor.description."""

    def __init__(self, name):
        self.name = name


def _detect_table(sql):
    """Detect which table a SQL statement targets.

    Dual-compatible: matches both old (core/vault) and new (local/obsidian) schema names.
    Returns: 'core', 'core_active', 'vault', 'meta', 'sync_queue', or 'unknown'
    """
    sql_upper = sql.upper()
    if "LOCAL.ACTIVE_MEMORIES" in sql_upper or "CORE.ACTIVE_MEMORIES" in sql_upper:
        return "core_active"
    if "LOCAL.SYNC_QUEUE" in sql_upper or "CORE.SYNC_QUEUE" in sql_upper:
        return "sync_queue"
    if "LOCAL.MEMORIES" in sql_upper or "CORE.MEMORIES" in sql_upper:
        return "core"
    if "OBSIDIAN.DOCUMENTS" in sql_upper or "VAULT.DOCUMENTS" in sql_upper:
        return "vault"
    if "LOCAL.META" in sql_upper or "CORE.META" in sql_upper:
        return "meta"
    # Legacy fallback
    if "JARVIS_META" in sql_upper:
        return "meta"
    if "FROM JARVIS" in sql_upper or "INTO JARVIS" in sql_upper or "UPDATE JARVIS" in sql_upper:
        return "core"
    return "unknown"


class MockCursor:
    """Translates SQL patterns from production code into InMemoryDB operations.

    Routes queries to the correct table (core.memories, vault.documents,
    core.meta) based on SQL pattern matching.
    """

    def __init__(self, db: InMemoryDB):
        self.db = db
        self._rows = []
        self._description = None
        self.rowcount = 0

    @property
    def description(self):
        return self._description

    def execute(self, sql, params=None):
        params = tuple(params) if params else ()
        sql_norm = " ".join(sql.split())
        sql_upper = sql_norm.upper()

        # Schema DDL — no-op
        if any(sql_upper.startswith(kw) for kw in ("CREATE ", "DO ", "ALTER ")):
            self._description = None
            return

        # pg_extension check — no-op
        if "PG_EXTENSION" in sql_upper:
            self._description = [_Col("extversion")]
            self._rows = [("0.8.0",)]
            return

        # Advisory lock — no-op
        if "PG_ADVISORY" in sql_upper:
            self._description = None
            return

        # to_regclass check
        if "TO_REGCLASS" in sql_upper:
            self._description = [_Col("to_regclass")]
            self._rows = [(None,)]  # fresh install by default
            return

        table = _detect_table(sql_norm)

        # INSERT
        if sql_upper.lstrip().startswith("INSERT"):
            if table == "meta":
                self._handle_meta_insert(sql_norm, params)
            elif table == "vault":
                self._handle_vault_insert(sql_norm, params)
            else:
                self._handle_core_insert(sql_norm, params)
            return

        # UPDATE
        if sql_upper.lstrip().startswith("UPDATE"):
            self._handle_core_update(sql_norm, params)
            return

        # DELETE
        if sql_upper.lstrip().startswith("DELETE"):
            if table == "vault":
                self._handle_vault_delete(sql_norm, params)
            else:
                self._handle_core_delete(sql_norm, params)
            return

        # SELECT
        if sql_upper.lstrip().startswith("SELECT"):
            if table == "meta":
                self._handle_meta_select(sql_norm, params)
            elif table in ("vault",):
                self._handle_vault_select(sql_norm, params)
            elif table in ("core", "core_active"):
                active_only = table == "core_active"
                self._handle_core_select(sql_norm, params, active_only)
            else:
                # Try to route by context
                if "PG_TOTAL_RELATION_SIZE" in sql_upper:
                    self._description = [_Col("total_bytes")]
                    self._rows = [(0,)]
                else:
                    self._handle_core_select(sql_norm, params, False)
            return

        # Unknown — no-op
        self._description = None
        self._rows = []
        self.rowcount = 0

    def executemany(self, sql, params_list):
        count = 0
        for p in params_list:
            self.execute(sql, p)
            count += self.rowcount
        self.rowcount = count

    def fetchone(self):
        return self._rows[0] if self._rows else None

    def fetchall(self):
        return list(self._rows)

    # ── Core INSERT handler ────────────────────────────────────────────

    def _handle_core_insert(self, sql, params):
        """INSERT INTO core.memories (...) VALUES (...) ON CONFLICT DO UPDATE."""
        sql_upper = sql.upper()

        # Detect column list from SQL
        col_match = re.search(r"INSERT INTO\s+\S+\s*\(([^)]+)\)", sql, re.I)
        if not col_match:
            # Fallback: legacy pattern (id, document, embedding, metadata, ...)
            self._handle_legacy_insert(sql, params)
            return

        cols = [c.strip().lower() for c in col_match.group(1).split(",")]

        # Parse VALUES clause to handle literal values vs %s placeholders
        vals_match = re.search(r"VALUES\s*\(([^)]+)\)", sql, re.I)
        if vals_match:
            val_tokens = [v.strip() for v in vals_match.group(1).split(",")]
            param_idx = 0
            vals = []
            for token in val_tokens:
                # Strip type casts like ::halfvec, ::jsonb
                clean = re.sub(r"::\w+", "", token).strip()
                if clean == "%s":
                    vals.append(params[param_idx] if param_idx < len(params) else None)
                    param_idx += 1
                else:
                    # Literal value in SQL (e.g. 0.0, 'active')
                    literal = clean.strip("'\"")
                    try:
                        literal = float(literal)
                    except (ValueError, TypeError):
                        pass
                    vals.append(literal)
        else:
            vals = list(params[:len(cols)])

        row_data = dict(zip(cols, vals))
        row_id = row_data.get("id", "")
        document = row_data.get("document", "")
        embedding = row_data.get("embedding", [])
        category = row_data.get("category", "observation")
        scope = row_data.get("scope", "global")
        project = row_data.get("project")
        source = row_data.get("source", "auto-extract")
        importance_score = float(row_data.get("importance_score", 0.5))
        retrieval_count = float(row_data.get("retrieval_count", 0.0))
        metadata_json = row_data.get("metadata", "{}")
        created_at = row_data.get("created_at")
        updated_at = row_data.get("updated_at")

        if isinstance(metadata_json, str):
            metadata = json.loads(metadata_json)
        elif isinstance(metadata_json, dict):
            metadata = dict(metadata_json)
        else:
            metadata = {}

        self.db.upsert_core(
            row_id, document, embedding,
            category=category, scope=scope, project=project,
            source=source, importance_score=importance_score,
            retrieval_count=retrieval_count, metadata=metadata,
            created_at=created_at, updated_at=updated_at,
        )
        self.rowcount = 1
        self._description = None
        self._rows = []

    def _handle_legacy_insert(self, sql, params):
        """Fallback for old-style INSERT INTO jarvis (id, doc, emb, meta, ...)."""
        row_id = params[0]
        document = params[1]
        embedding = params[2]
        metadata_json = params[3]
        created_at = params[4] if len(params) > 4 else None
        updated_at = params[5] if len(params) > 5 else None
        self.db.upsert(row_id, document, embedding, metadata_json, created_at, updated_at)
        self.rowcount = 1
        self._description = None
        self._rows = []

    # ── Vault INSERT handler ────────────────────────────────────────────

    def _handle_vault_insert(self, sql, params):
        """INSERT INTO vault.documents (...) VALUES (...) ON CONFLICT DO UPDATE."""
        col_match = re.search(r"INSERT INTO\s+\S+\s*\(([^)]+)\)", sql, re.I)
        if not col_match:
            return

        cols = [c.strip().lower() for c in col_match.group(1).split(",")]
        vals = list(params[:len(cols)])

        row_data = dict(zip(cols, vals))
        row_id = row_data.get("id", "")
        document = row_data.get("document", "")
        embedding = row_data.get("embedding", [])
        parent_file = row_data.get("parent_file", "")
        directory = row_data.get("directory", "")
        vault_type = row_data.get("vault_type", "document")
        title = row_data.get("title", "")
        chunk_index = int(row_data.get("chunk_index", 0))
        chunk_total = int(row_data.get("chunk_total", 1))
        chunk_heading = row_data.get("chunk_heading", "")
        importance_score = float(row_data.get("importance_score", 0.5))
        metadata_json = row_data.get("metadata", "{}")

        if isinstance(metadata_json, str):
            metadata = json.loads(metadata_json)
        elif isinstance(metadata_json, dict):
            metadata = dict(metadata_json)
        else:
            metadata = {}

        self.db.upsert_vault(
            row_id, document, embedding,
            parent_file=parent_file, directory=directory,
            vault_type=vault_type, title=title,
            chunk_index=chunk_index, chunk_total=chunk_total,
            chunk_heading=chunk_heading, importance_score=importance_score,
            metadata=metadata,
        )
        self.rowcount = 1
        self._description = None
        self._rows = []

    # ── Meta handlers ────────────────────────────────────────────────

    def _handle_meta_insert(self, sql, params):
        """INSERT INTO core.meta (key, value) VALUES (%s, %s) ON CONFLICT DO UPDATE."""
        key = params[0]
        value = params[1]
        if isinstance(value, str):
            value = json.loads(value)
        now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        self.db.meta_rows[key] = {"key": key, "value": value, "updated_at": now}
        self.rowcount = 1
        self._description = None
        self._rows = []

    def _handle_meta_select(self, sql, params):
        """Handle SELECT from core.meta (single key or all)."""
        if "WHERE" in sql.upper() and params:
            key = params[0]
            row = self.db.meta_rows.get(key)
            if row:
                self._description = [_Col("value")]
                self._rows = [(row["value"],)]
            else:
                self._description = [_Col("value")]
                self._rows = []
        else:
            self._description = [_Col("key"), _Col("value")]
            self._rows = [(r["key"], r["value"]) for r in self.db.meta_rows.values()]

    # ── Core UPDATE handler ────────────────────────────────────────────

    def _handle_core_update(self, sql, params):
        sql_upper = sql.upper()
        has_returning = "RETURNING" in sql_upper
        has_any = "ANY(" in sql_upper

        if has_any:
            # Batch update: WHERE id = ANY(%s)
            # retrieval_count batch increment
            if "RETRIEVAL_COUNT" in sql_upper:
                increment = float(params[0])
                ids = params[-1]
                updated = 0
                for rid in ids:
                    row = self.db.core_rows.get(rid)
                    if row:
                        row["retrieval_count"] = row.get("retrieval_count", 0.0) + increment
                        now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
                        row["updated_at"] = now
                        updated += 1
                self.rowcount = updated
            else:
                self.rowcount = 0
            self._description = None
            self._rows = []
            return

        # Single row updates
        doc_id = params[-1]
        row = self.db.core_rows.get(doc_id)

        if not row:
            self.rowcount = 0
            self._description = None
            self._rows = []
            return

        if "STATUS = 'SUPERSEDED'" in sql_upper:
            # Check for AND status = 'active' condition
            if "AND STATUS = 'ACTIVE'" in sql_upper and row.get("status") != "active":
                self.rowcount = 0
                self._description = None
                self._rows = []
                return
            row["status"] = "superseded"
            row["superseded_by"] = params[0]
            now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
            row["updated_at"] = now
        elif "STATUS = 'DELETED'" in sql_upper:
            row["status"] = "deleted"
            now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
            row["deleted_at"] = now
            row["updated_at"] = now
        elif "RETRIEVAL_COUNT" in sql_upper:
            # Check status filter before updating
            if "AND STATUS = 'ACTIVE'" in sql_upper and row.get("status") != "active":
                self.rowcount = 0
                self._description = None
                self._rows = []
                return
            if "RETRIEVAL_COUNT + %S" in sql_upper or "RETRIEVAL_COUNT + 1" in sql_upper:
                if "+ %S" in sql.upper():
                    increment = float(params[0])
                else:
                    increment = 1.0
                row["retrieval_count"] = row.get("retrieval_count", 0.0) + increment
            now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
            row["updated_at"] = now
        elif "DOCUMENT = %S" in sql_upper:
            # content_upsert: update document + metadata + importance etc
            # Params vary by what's being updated
            # Simple approach: just update document if present
            idx = 0
            if "document = %s" in sql.lower():
                row["document"] = params[idx]
                idx += 1
            if "importance_score = %s" in sql.lower():
                row["importance_score"] = float(params[idx])
                idx += 1
            now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
            row["updated_at"] = now
        else:
            # Generic metadata update via JSONB merge (legacy)
            if "jsonb_build_object" in sql.lower():
                if "superseded" in sql.lower():
                    row["status"] = "superseded"
                    row["superseded_by"] = params[0]
            now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
            row["updated_at"] = now

        self.rowcount = 1

        if has_returning:
            ret_match = re.search(r"RETURNING\s+(.*?)$", sql, re.I)
            cols = (
                [c.strip() for c in ret_match.group(1).split(",")]
                if ret_match
                else ["id", "document", "metadata"]
            )
            self._description = [_Col(c) for c in cols]
            self._rows = [tuple(row.get(c) for c in cols)]
        else:
            self._description = None
            self._rows = []

    # ── DELETE handlers ────────────────────────────────────────────────

    def _handle_core_delete(self, sql, params):
        if "WHERE id = %s" in sql.lower() or "WHERE id = %s" in sql:
            deleted = self.db.delete_core(params[0])
            self.rowcount = 1 if deleted else 0
        else:
            self.rowcount = 0
        self._description = None
        self._rows = []

    def _handle_vault_delete(self, sql, params):
        if "parent_file" in sql.lower():
            count = self.db.delete_vault_where("parent_file", params[0])
            self.rowcount = count
        elif "WHERE id = %s" in sql.lower():
            deleted = self.db.delete_vault(params[0])
            self.rowcount = 1 if deleted else 0
        else:
            self.rowcount = 0
        self._description = None
        self._rows = []

    # ── Core SELECT handler ────────────────────────────────────────────

    def _handle_core_select(self, sql, params, active_only=False):
        sql_upper = sql.upper()

        # pg_total_relation_size
        if "PG_TOTAL_RELATION_SIZE" in sql_upper:
            self._description = [_Col("total_bytes")]
            self._rows = [(0,)]
            return

        # GROUP BY (collection_stats)
        if "GROUP BY" in sql_upper:
            self._handle_core_group_by(sql, params, active_only)
            return

        # COUNT(*)
        if "COUNT(*)" in sql_upper:
            conditions = self._extract_column_conditions(sql, params)
            rows = self.db._filter_rows(self.db.core_rows, conditions, active_only)
            alias_match = re.search(r"count\(\*\)\s+AS\s+(\w+)", sql, re.I)
            col = alias_match.group(1) if alias_match else "cnt"
            self._description = [_Col(col)]
            self._rows = [(len(rows),)]
            return

        # Vector search (embedding <=>)
        if "embedding <=>" in sql:
            self._handle_core_vector_search(sql, params, active_only)
            return

        # Batch get: ANY(%s)
        if "ANY(" in sql_upper:
            ids = params[0] if params else []
            rows = self.db.get_many_core(ids)
            self._set_core_results(sql, rows)
            return

        # Single get: WHERE id = %s
        if re.search(r"WHERE\s+id\s*=\s*%s", sql, re.I):
            row = self.db.get_core(params[0]) if params else None
            rows = [row] if row else []
            if active_only:
                rows = [r for r in rows if r.get("status") == "active"]
            self._set_core_results(sql, rows)
            return

        # Filtered query (column conditions)
        conditions = self._extract_column_conditions(sql, params)
        order_by = self._extract_order_by(sql)
        limit_val = self._extract_limit(sql, params, len([c for c in conditions]))
        rows = self.db.list_core(conditions, order_by, limit_val, active_only)
        self._set_core_results(sql, rows)

    def _handle_core_vector_search(self, sql, params, active_only=False):
        # In vector search queries the embedding %s appears in the SELECT
        # clause (before WHERE), so it's always params[0].  Column conditions
        # in the WHERE clause consume params[1..N-1], and LIMIT is params[-1].
        query_embedding = params[0] if params else []

        # Extract WHERE conditions using params shifted past the embedding
        conditions = self._extract_column_conditions(sql, params[1:]) if len(params) > 1 else []
        param_offset = 1 + len(conditions)

        limit = 10
        if len(params) > param_offset:
            try:
                limit = int(params[-1])
            except (ValueError, TypeError):
                limit = 10

        results = self.db.vector_search_core(query_embedding, limit, conditions, active_only)

        # Inject _schema for cross-schema query support (dynamic: local or core)
        schema_val = "local" if "LOCAL." in sql.upper() else "core"
        for r in results:
            r["_schema"] = schema_val

        # Build columns from SELECT clause
        cols = self._extract_select_columns(sql)
        if "distance" not in cols:
            cols.append("distance")
        # Resolve literal aliases (e.g., 'core' AS _schema)
        literals = self._extract_literal_aliases(sql)
        self._description = [_Col(c) for c in cols]
        self._rows = [tuple(literals.get(c, r.get(c)) for c in cols) for r in results]

    def _handle_core_group_by(self, sql, params, active_only=False):
        rows = list(self.db.core_rows.values())
        if active_only:
            rows = [r for r in rows if r.get("status") == "active"]

        if "category" in sql.lower():
            groups = Counter(r.get("category", "unknown") for r in rows)
            self._description = [_Col("category"), _Col("cnt")]
            self._rows = [(t, c) for t, c in groups.most_common(20)]
        elif "scope" in sql.lower():
            groups = Counter(r.get("scope", "global") for r in rows)
            self._description = [_Col("scope"), _Col("cnt")]
            self._rows = [(s, c) for s, c in groups.most_common(20)]
        else:
            self._description = [_Col("key"), _Col("cnt")]
            self._rows = []

    def _set_core_results(self, sql, rows):
        cols = self._extract_select_columns(sql)
        if not cols:
            cols = ["id", "document", "metadata"]
        self._description = [_Col(c) for c in cols]
        self._rows = [tuple(r.get(c) for c in cols) for r in rows]

    # ── Vault SELECT handler ────────────────────────────────────────────

    def _handle_vault_select(self, sql, params):
        sql_upper = sql.upper()

        # pg_total_relation_size
        if "PG_TOTAL_RELATION_SIZE" in sql_upper:
            self._description = [_Col("total_bytes")]
            self._rows = [(0,)]
            return

        # GROUP BY
        if "GROUP BY" in sql_upper:
            rows = list(self.db.vault_rows.values())
            if "vault_type" in sql.lower():
                groups = Counter(r.get("vault_type", "document") for r in rows)
                self._description = [_Col("vault_type"), _Col("cnt")]
                self._rows = [(t, c) for t, c in groups.most_common(20)]
            elif "directory" in sql.lower():
                groups = Counter(r.get("directory", "") for r in rows)
                self._description = [_Col("directory"), _Col("cnt")]
                self._rows = [(d, c) for d, c in groups.most_common(20)]
            else:
                self._description = [_Col("key"), _Col("cnt")]
                self._rows = []
            return

        # COUNT(*)
        if "COUNT(*)" in sql_upper:
            conditions = self._extract_vault_conditions(sql, params)
            rows = self.db._filter_rows(self.db.vault_rows, conditions)
            alias_match = re.search(r"count\(\*\)\s+AS\s+(\w+)", sql, re.I)
            col = alias_match.group(1) if alias_match else "cnt"
            self._description = [_Col(col)]
            self._rows = [(len(rows),)]
            return

        # DISTINCT parent_file
        if "DISTINCT" in sql_upper and "PARENT_FILE" in sql_upper:
            files = set(r.get("parent_file", "") for r in self.db.vault_rows.values())
            self._description = [_Col("parent_file")]
            self._rows = [(f,) for f in sorted(files)]
            return

        # Vector search (embedding <=>)
        if "embedding <=>" in sql:
            self._handle_vault_vector_search(sql, params)
            return

        # Batch get: ANY(%s)
        if "ANY(" in sql_upper:
            ids = params[0] if params else []
            rows = self.db.get_many_vault(ids)
            self._set_vault_results(sql, rows)
            return

        # Single get: WHERE id = %s
        if re.search(r"WHERE\s+id\s*=\s*%s", sql, re.I):
            row = self.db.get_vault(params[0]) if params else None
            rows = [row] if row else []
            self._set_vault_results(sql, rows)
            return

        # Filtered query
        conditions = self._extract_vault_conditions(sql, params)
        order_by = self._extract_order_by(sql)
        limit_val = self._extract_limit(sql, params, len(conditions))
        rows = self.db.list_vault(conditions, order_by, limit_val)
        self._set_vault_results(sql, rows)

    def _handle_vault_vector_search(self, sql, params):
        conditions = self._extract_vault_conditions(sql, params)
        param_offset = len(conditions)

        query_embedding = params[param_offset] if param_offset < len(params) else []
        limit = 10
        if len(params) > param_offset + 1:
            try:
                limit = int(params[-1])
            except (ValueError, TypeError):
                limit = 10

        results = self.db.vector_search_vault(query_embedding, limit, conditions)

        # Inject _schema for cross-schema query support (dynamic: obsidian or vault)
        schema_val = "obsidian" if "OBSIDIAN." in sql.upper() else "vault"
        for r in results:
            r["_schema"] = schema_val

        cols = self._extract_select_columns(sql)
        if "distance" not in cols:
            cols.append("distance")
        # Resolve literal aliases (e.g., 'vault' AS _schema)
        literals = self._extract_literal_aliases(sql)
        self._description = [_Col(c) for c in cols]
        self._rows = [tuple(literals.get(c, r.get(c)) for c in cols) for r in results]

    def _set_vault_results(self, sql, rows):
        cols = self._extract_select_columns(sql)
        if not cols:
            cols = ["id", "document", "metadata"]
        self._description = [_Col(c) for c in cols]
        self._rows = [tuple(r.get(c) for c in cols) for r in rows]

    # ── Result helpers ────────────────────────────────────────────────

    def _extract_select_columns(self, sql):
        m = re.search(r"SELECT\s+(.*?)\s+FROM", sql, re.I | re.S)
        if not m:
            return ["id", "document", "metadata"]

        select_part = m.group(1).strip()
        if select_part == "*":
            return ["id", "document", "metadata"]

        cols = []
        for part in select_part.split(","):
            part = part.strip()
            # Skip DISTINCT keyword
            if part.upper().startswith("DISTINCT "):
                part = part[9:].strip()
            # Handle "expr AS alias"
            alias_match = re.search(r"\bAS\s+(\w+)\s*$", part, re.I)
            if alias_match:
                cols.append(alias_match.group(1))
                continue
            # Handle "embedding <=> %s::halfvec" -> "distance"
            if "<=>" in part:
                cols.append("distance")
                continue
            # Simple column name (strip type casts)
            clean = re.sub(r"::\w+", "", part)
            clean = re.sub(r"\(.*?\)", "", clean)
            clean = clean.strip()
            if clean and clean.upper() not in ("DISTINCT",):
                cols.append(clean)

        return cols if cols else ["id", "document", "metadata"]

    def _extract_literal_aliases(self, sql):
        """Extract literal value aliases like 'core' AS _schema from SELECT."""
        literals = {}
        m = re.search(r"SELECT\s+(.*?)\s+FROM", sql, re.I | re.S)
        if m:
            for part in m.group(1).split(","):
                part = part.strip()
                lit_match = re.search(r"'(\w+)'\s+AS\s+(\w+)\s*$", part, re.I)
                if lit_match:
                    literals[lit_match.group(2)] = lit_match.group(1)
        return literals

    # ── SQL parsing helpers ───────────────────────────────────────────

    def _extract_column_conditions(self, sql, params):
        """Extract column-based conditions from WHERE clause for core.memories."""
        conditions = []
        param_idx = 0

        # Match column conditions: column = %s, column >= %s
        # (?<!%) prevents matching 's' from '%s' as a column name
        for m in re.finditer(
            r"(?:AND\s+)?(?<!%)(\w+)\s*(=|>=|LIKE)\s*(%s|'([^']*)')",
            sql,
        ):
            col = m.group(1).lower()
            op = m.group(2)
            # Skip 'id' conditions (handled separately) and embedding params
            if col in ("id", "embedding"):
                continue
            if m.group(3) == "%s":
                if param_idx < len(params):
                    value = params[param_idx]
                    param_idx += 1
                else:
                    continue
            else:
                value = m.group(4)
            conditions.append((col, op, value))

        # Also check for metadata JSONB conditions (backward compat)
        for m in re.finditer(
            r"metadata->>'(\w+)'\)?(?:::float)?\s*(=|>=|LIKE)\s*(%s|'([^']*)')",
            sql,
        ):
            key = m.group(1)
            op = m.group(2)
            if m.group(3) == "%s":
                if param_idx < len(params):
                    value = params[param_idx]
                    param_idx += 1
                else:
                    continue
            else:
                value = m.group(4)
            # Route to metadata sub-dict
            conditions.append(("_meta_" + key, op, value))

        # Generic JSONB: metadata->>%s = %s (parameterized key and value)
        for m in re.finditer(
            r"metadata->>%s\s*(=|>=|LIKE)\s*%s",
            sql,
        ):
            op = m.group(1)
            if param_idx + 1 < len(params):
                key = params[param_idx]
                value = params[param_idx + 1]
                param_idx += 2
                conditions.append(("_meta_" + key, op, value))

        return conditions

    def _extract_vault_conditions(self, sql, params):
        """Extract column-based conditions from WHERE clause for vault.documents."""
        conditions = []
        param_idx = 0

        for m in re.finditer(
            r"(?:AND\s+)?(\w+)\s*(=|>=|LIKE)\s*(%s|'([^']*)')",
            sql,
        ):
            col = m.group(1).lower()
            op = m.group(2)
            if col in ("id", "embedding"):
                continue
            if m.group(3) == "%s":
                if param_idx < len(params):
                    value = params[param_idx]
                    param_idx += 1
                else:
                    continue
            else:
                value = m.group(4)
            conditions.append((col, op, value))

        return conditions

    def _extract_order_by(self, sql):
        # ORDER BY column ASC/DESC (but not 'distance')
        m = re.search(r"ORDER BY\s+(\w+)\s+(ASC|DESC)", sql, re.I)
        if m and m.group(1).lower() not in ("distance",):
            return (m.group(1), m.group(2).upper())
        return None

    def _extract_limit(self, sql, params, param_offset):
        if re.search(r"LIMIT\s+%s", sql, re.I):
            if param_offset < len(params):
                try:
                    return int(params[param_offset])
                except (ValueError, TypeError):
                    pass
        m = re.search(r"LIMIT\s+(\d+)", sql, re.I)
        if m:
            return int(m.group(1))
        return None


class MockConnection:
    """Mock psycopg connection backed by InMemoryDB."""

    def __init__(self, db: InMemoryDB):
        self.db = db

    def cursor(self):
        return _CursorCtx(self.db)

    def execute(self, sql, params=None):
        """For conn.execute() calls (schema DDL)."""
        cur = MockCursor(self.db)
        cur.execute(sql, params)
        return cur

    def transaction(self):
        """Mock of psycopg's per-row transaction/savepoint context manager.

        The in-memory store writes immediately (no real transactions), so
        this is a transparent passthrough. It does NOT suppress exceptions,
        mirroring psycopg where a failing block rolls back and re-raises —
        which is what _upsert_batch relies on to record per-row failures.
        """
        return _TxnCtx()

    def commit(self):
        pass


class _TxnCtx:
    """Context manager wrapping a mock transaction/savepoint (no-op)."""

    def __enter__(self):
        return self

    def __exit__(self, *args):
        return False


class _CursorCtx:
    """Context manager wrapping MockCursor."""

    def __init__(self, db):
        self._cursor = MockCursor(db)

    def __enter__(self):
        return self._cursor

    def __exit__(self, *args):
        pass


class _ConnCtx:
    """Context manager wrapping MockConnection."""

    def __init__(self, db):
        self._conn = MockConnection(db)

    def __enter__(self):
        return self._conn

    def __exit__(self, *args):
        pass


class MockPool:
    """Mock psycopg_pool.ConnectionPool backed by InMemoryDB."""

    def __init__(self, db: InMemoryDB):
        self.db = db

    def connection(self):
        return _ConnCtx(self.db)

    def close(self):
        pass


# ── Pytest fixtures ────────────────────────────────────────────────────


@pytest.fixture
def temp_vault() -> Generator[Path, None, None]:
    """Create a temporary vault directory for testing."""
    with tempfile.TemporaryDirectory(prefix="jarvis_test_vault_") as tmpdir:
        vault_path = Path(tmpdir)
        # Create some structure
        (vault_path / "journal" / "2026" / "01").mkdir(parents=True)
        (vault_path / "notes").mkdir()
        (vault_path / "inbox").mkdir()
        # Initialize as git repo (some tests may need this)
        os.system(f"cd {vault_path} && git init -q")
        yield vault_path


@pytest.fixture
def temp_config_dir() -> Generator[Path, None, None]:
    """Create a temporary config directory."""
    with tempfile.TemporaryDirectory(prefix="jarvis_test_config_") as tmpdir:
        yield Path(tmpdir)


@pytest.fixture
def mock_config(temp_vault: Path, temp_config_dir: Path, monkeypatch):
    """Mock the config module to use temporary paths and in-memory pgvector.

    Patches:
    - Config: uses temp vault + config directory
    - Schema: _get_pool returns MockPool backed by InMemoryDB
    - Embedding: get_embedding_service returns MockEmbeddingService
    """
    import tools.config as config_module
    import jarvis_common.config as common_config_module
    import tools.schema as schema_module
    import tools.embedding as embedding_module

    # Clear all caches
    config_module._config_cache = None
    common_config_module._config_cache = None
    schema_module._pool = None
    schema_module._pool_cache_key = None
    embedding_module._service = None
    embedding_module._service_cache_key = None

    # Create shared in-memory database
    db = InMemoryDB()

    # Create a valid config
    config_file = temp_config_dir / "config.json"
    # Use temp dirs for absolute paths that default to ~/.jarvis/
    temp_memories = temp_config_dir / "memories"
    temp_memories.mkdir(exist_ok=True)
    config_data = {
        "vault_path": str(temp_vault),
        "vault_confirmed": True,
        "configured_at": "2026-02-02T12:00:00Z",
        "memory": {
            "postgres_url": "postgresql://test:test@localhost:5432/jarvis_test",
            "project_memories_path": str(temp_memories),
        },
    }
    config_file.write_text(json.dumps(config_data))

    # Monkey-patch config in BOTH modules
    def mock_get_config():
        if common_config_module._config_cache is None:
            if config_file.exists():
                common_config_module._config_cache = json.loads(config_file.read_text())
            else:
                common_config_module._config_cache = {}
        return common_config_module._config_cache

    monkeypatch.setattr(common_config_module, "get_config", mock_get_config)
    monkeypatch.setattr(config_module, "get_config", mock_get_config)

    # Patch schema._get_pool to return MockPool
    mock_pool = MockPool(db)
    monkeypatch.setattr(schema_module, "_get_pool", lambda: mock_pool)
    monkeypatch.setattr(schema_module, "_pool", mock_pool)
    monkeypatch.setattr(schema_module, "_pool_cache_key", ("test", 384))

    # Patch embedding service
    mock_emb = MockEmbeddingService(dimensions=384)
    monkeypatch.setattr(embedding_module, "get_embedding_service", lambda: mock_emb)
    monkeypatch.setattr(embedding_module, "_service", mock_emb)
    monkeypatch.setattr(
        embedding_module, "_service_cache_key", ("mock", 384, "cpu", "mock")
    )

    def _clear_cache():
        config_module._config_cache = None
        common_config_module._config_cache = None

    class ConfigHelper:
        def __init__(self):
            self.path = config_file
            self.vault_path = temp_vault
            self.db = db  # In-memory database for direct test manipulation

        def set(self, **kwargs):
            """Update config values."""
            data = json.loads(self.path.read_text()) if self.path.exists() else {}
            data.update(kwargs)
            self.path.write_text(json.dumps(data))
            _clear_cache()

        def delete_key(self, key: str):
            """Remove a key from config."""
            data = json.loads(self.path.read_text())
            data.pop(key, None)
            self.path.write_text(json.dumps(data))
            _clear_cache()

        def delete_file(self):
            """Delete the config file entirely."""
            if self.path.exists():
                self.path.unlink()
            _clear_cache()

    return ConfigHelper()


@pytest.fixture
def unconfirmed_config(mock_config):
    """Config without vault_confirmed flag."""
    mock_config.delete_key("vault_confirmed")
    return mock_config


@pytest.fixture
def no_config(mock_config):
    """No config file exists."""
    mock_config.delete_file()
    return mock_config


@pytest.fixture(autouse=True)
def cleanup_db_state():
    """Clean up database and config caches after each test."""
    yield
    import tools.config as config_module
    import jarvis_common.config as common_config_module
    import tools.schema as schema_module
    import tools.embedding as embedding_module

    config_module._config_cache = None
    common_config_module._config_cache = None
    schema_module._pool = None
    schema_module._pool_cache_key = None
    embedding_module._service = None
    embedding_module._service_cache_key = None


@pytest.fixture
def git_repo(temp_vault: Path) -> Path:
    """Vault with initialized git repo and sample commits."""
    # Git repo already initialized in temp_vault
    os.system(f'cd {temp_vault} && git config user.email "test@example.com"')
    os.system(f'cd {temp_vault} && git config user.name "Test User"')

    # Create initial commit
    test_file = temp_vault / "test.txt"
    test_file.write_text("Initial content")
    os.system(
        f'cd {temp_vault} && git add test.txt && git commit -q -m "Initial commit"'
    )
    return temp_vault


@pytest.fixture
def git_repo_with_jarvis_commits(git_repo: Path) -> Path:
    """Git repo with sample JARVIS protocol commits."""
    journal_file = git_repo / "journal" / "2026" / "01" / "20260123153045-test-entry.md"
    journal_file.write_text("# Test Entry\n\nTest content")

    os.system(f"cd {git_repo} && git add {journal_file}")
    commit_msg = "Jarvis CREATE: Test journal entry\n\n[JARVIS:Cc:20260123153045]"
    os.system(f'cd {git_repo} && git commit -q -m "{commit_msg}"')

    note_file = git_repo / "notes" / "test-note.md"
    note_file.write_text("# Test Note")
    os.system(f"cd {git_repo} && git add {note_file}")
    edit_msg = "Jarvis EDIT: Update test note\n\n[JARVIS:Ea]"
    os.system(f'cd {git_repo} && git commit -q -m "{edit_msg}"')

    return git_repo


@pytest.fixture
def mock_subprocess(monkeypatch):
    """Mock subprocess.run for testing command failures."""
    import subprocess
    from unittest.mock import Mock

    class SubprocessMock:
        def __init__(self):
            self.call_count = 0
            self.mock_return = None
            self.mock_side_effect = None

        def set_return(self, returncode=0, stdout="", stderr=""):
            result = Mock()
            result.returncode = returncode
            result.stdout = stdout
            result.stderr = stderr
            self.mock_return = result

        def set_side_effect(self, side_effect):
            self.mock_side_effect = side_effect

        def __call__(self, *args, **kwargs):
            self.call_count += 1
            if self.mock_side_effect:
                if isinstance(self.mock_side_effect, Exception):
                    raise self.mock_side_effect
                return self.mock_side_effect(*args, **kwargs)
            return (
                self.mock_return
                if self.mock_return
                else Mock(returncode=0, stdout="", stderr="")
            )

    mock = SubprocessMock()
    monkeypatch.setattr(subprocess, "run", mock)
    return mock
