"""Pytest fixtures for Jarvis Tools tests.

Provides mock PostgreSQL + pgvector infrastructure via InMemoryDB, allowing
tests to run without a real database. The MockPool/MockCursor translate SQL
patterns generated by production code into in-memory dict operations.
"""

import hashlib
import json
import math
import os
import re
import tempfile
from collections import Counter
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Generator
from unittest.mock import MagicMock

import pytest


# ── Mock Embedding Service ─────────────────────────────────────────────


class MockEmbeddingService:
    """Returns deterministic 768d vectors based on text content hash.

    Similar texts produce similar vectors (via SHA-256 hash),
    enabling realistic vector search in tests.
    """

    def __init__(self, dimensions=768):
        self._dimensions = dimensions

    def encode(self, text: str) -> list[float]:
        h = hashlib.sha256(text.encode()).digest()
        vec = [(h[i % len(h)] / 255.0) * 2 - 1 for i in range(self._dimensions)]
        norm = math.sqrt(sum(x * x for x in vec))
        return [x / norm for x in vec] if norm > 0 else vec

    def encode_batch(self, texts: list[str], batch_size: int = 64) -> list[list[float]]:
        return [self.encode(t) for t in texts]

    @property
    def dimensions(self) -> int:
        return self._dimensions

    @property
    def model_name(self) -> str:
        return "mock-model"

    @property
    def backend(self) -> str:
        return "mock"

    @property
    def is_loaded(self) -> bool:
        return True


# ── In-memory PostgreSQL mock ──────────────────────────────────────────


def _cosine_distance(a, b):
    """Cosine distance: 0 = identical, 2 = opposite."""
    if not a or not b:
        return 1.0
    min_len = min(len(a), len(b))
    a, b = a[:min_len], b[:min_len]
    dot = sum(x * y for x, y in zip(a, b))
    norm_a = math.sqrt(sum(x * x for x in a))
    norm_b = math.sqrt(sum(x * x for x in b))
    if norm_a == 0 or norm_b == 0:
        return 1.0
    return max(0.0, 1.0 - (dot / (norm_a * norm_b)))


class InMemoryDB:
    """In-memory mock for the jarvis PostgreSQL table.

    Stores documents as dicts: {id, document, embedding, metadata, created_at, updated_at}.
    Metadata is always a Python dict (like psycopg's auto-deserialized JSONB).
    """

    def __init__(self):
        self.rows = {}  # id -> row dict
        self.meta_rows = {}  # key -> {key, value, updated_at}

    def upsert(self, row_id, document, embedding, metadata_json, created_at=None, updated_at=None):
        now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        if isinstance(metadata_json, str):
            meta = json.loads(metadata_json)
        elif isinstance(metadata_json, dict):
            meta = dict(metadata_json)
        else:
            meta = {}

        existing = self.rows.get(row_id)
        self.rows[row_id] = {
            "id": row_id,
            "document": document,
            "embedding": embedding if isinstance(embedding, list) else list(embedding or []),
            "metadata": meta,
            "created_at": created_at or (existing["created_at"] if existing else now),
            "updated_at": updated_at or now,
        }

    def get(self, row_id):
        row = self.rows.get(row_id)
        return dict(row) if row else None

    def get_many(self, ids):
        return [dict(self.rows[rid]) for rid in ids if rid in self.rows]

    def delete(self, row_id):
        return self.rows.pop(row_id, None) is not None

    def delete_where_metadata(self, key, value):
        to_delete = [
            rid for rid, row in self.rows.items()
            if row["metadata"].get(key) == value
        ]
        for rid in to_delete:
            del self.rows[rid]
        return len(to_delete)

    def count(self, conditions=None):
        return len(self._filter(conditions))

    def _filter(self, conditions=None):
        rows = list(self.rows.values())
        if not conditions:
            return rows
        for key, op, value in conditions:
            if op == "=":
                # Compare directly — avoids str(Enum) producing qualified name
                # (e.g. str(ContentType.OBSERVATION) → "ContentType.OBSERVATION"
                #  but json-stored value is "observation")
                val_cmp = value if isinstance(value, str) else str(value)
                rows = [r for r in rows if r["metadata"].get(key, "") == val_cmp]
            elif op == ">=":
                try:
                    fval = float(value)
                    rows = [r for r in rows if float(r["metadata"].get(key, 0)) >= fval]
                except (ValueError, TypeError):
                    pass
            elif op == "LIKE":
                pattern = re.escape(str(value)).replace(r"\%", ".*")
                rows = [
                    r for r in rows
                    if re.search(pattern, str(r["metadata"].get(key, "")))
                ]
        return rows

    def list_filtered(self, conditions=None, order_by=None, limit=None):
        rows = [dict(r) for r in self._filter(conditions)]
        if order_by:
            field, direction = order_by
            reverse = direction == "DESC"

            def sort_key(r):
                if field in ("created_at", "updated_at"):
                    return r.get(field, "")
                return float(r["metadata"].get(field, 0))

            try:
                rows.sort(key=sort_key, reverse=reverse)
            except (ValueError, TypeError):
                pass
        if limit:
            rows = rows[:limit]
        return rows

    def vector_search(self, query_embedding, limit, conditions=None):
        rows = [dict(r) for r in self._filter(conditions)]
        for r in rows:
            r["distance"] = _cosine_distance(query_embedding, r.get("embedding", []))
        rows.sort(key=lambda r: r["distance"])
        return rows[:limit]

    def clear(self):
        self.rows.clear()
        self.meta_rows.clear()


# ── Mock psycopg cursor / connection / pool ────────────────────────────


class _Col:
    """Minimal column descriptor for cursor.description."""

    def __init__(self, name):
        self.name = name


class MockCursor:
    """Translates SQL patterns from production code into InMemoryDB operations.

    Handles the ~10 SQL patterns generated by the rewritten pgvector modules.
    NOT a general SQL parser — only routes patterns the production code emits.
    """

    def __init__(self, db: InMemoryDB):
        self.db = db
        self._rows = []
        self._description = None
        self.rowcount = 0

    @property
    def description(self):
        return self._description

    def execute(self, sql, params=None):
        params = tuple(params) if params else ()
        sql_norm = " ".join(sql.split())
        sql_upper = sql_norm.upper()

        # Schema DDL — no-op
        if any(sql_upper.startswith(kw) for kw in ("CREATE ", "DO ")):
            self._description = None
            return

        # INSERT INTO jarvis_meta (upsert) — must come before generic jarvis check
        if "INSERT INTO JARVIS_META" in sql_upper:
            self._handle_meta_insert(sql_norm, params)
            return

        # INSERT INTO jarvis (upsert)
        if "INSERT INTO JARVIS" in sql_upper:
            self._handle_insert(sql_norm, params)
            return

        # UPDATE
        if sql_upper.lstrip().startswith("UPDATE"):
            self._handle_update(sql_norm, params)
            return

        # DELETE
        if sql_upper.lstrip().startswith("DELETE"):
            self._handle_delete(sql_norm, params)
            return

        # SELECT
        if sql_upper.lstrip().startswith("SELECT"):
            self._handle_select(sql_norm, params)
            return

        # Unknown — no-op
        self._description = None
        self._rows = []
        self.rowcount = 0

    def executemany(self, sql, params_list):
        count = 0
        for p in params_list:
            self.execute(sql, p)
            count += self.rowcount
        self.rowcount = count

    def fetchone(self):
        return self._rows[0] if self._rows else None

    def fetchall(self):
        return list(self._rows)

    # ── INSERT handler ────────────────────────────────────────────────

    def _handle_insert(self, sql, params):
        """INSERT INTO jarvis (...) VALUES (%s, ...) ON CONFLICT DO UPDATE."""
        row_id = params[0]
        document = params[1]
        embedding = params[2]
        metadata_json = params[3]
        created_at = params[4] if len(params) > 4 else None
        updated_at = params[5] if len(params) > 5 else None
        self.db.upsert(row_id, document, embedding, metadata_json, created_at, updated_at)
        self.rowcount = 1
        self._description = None
        self._rows = []

    # ── jarvis_meta handlers ────────────────────────────────────────

    def _handle_meta_insert(self, sql, params):
        """INSERT INTO jarvis_meta (key, value) VALUES (%s, %s) ON CONFLICT DO UPDATE."""
        key = params[0]
        value = params[1]
        if isinstance(value, str):
            value = json.loads(value)
        now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        self.db.meta_rows[key] = {"key": key, "value": value, "updated_at": now}
        self.rowcount = 1
        self._description = None
        self._rows = []

    def _handle_meta_select(self, sql, params):
        """Handle SELECT from jarvis_meta (single key or all)."""
        if "WHERE" in sql.upper() and params:
            # Single key lookup
            key = params[0]
            row = self.db.meta_rows.get(key)
            if row:
                self._description = [_Col("value")]
                self._rows = [(row["value"],)]
            else:
                self._description = [_Col("value")]
                self._rows = []
        else:
            # All rows
            self._description = [_Col("key"), _Col("value")]
            self._rows = [(r["key"], r["value"]) for r in self.db.meta_rows.values()]

    # ── UPDATE handler ────────────────────────────────────────────────

    def _handle_update(self, sql, params):
        sql_upper = sql.upper()
        has_returning = "RETURNING" in sql_upper
        has_any = "ANY(" in sql_upper

        if has_any:
            # Batch update: WHERE id = ANY(%s)
            # Params: (increment, updated_at, ids_list)
            increment = float(params[0])
            updated_at_val = params[1]
            ids = params[2]
            updated = 0
            for rid in ids:
                row = self.db.rows.get(rid)
                if row:
                    meta = row["metadata"]
                    current = float(meta.get("retrieval_count", 0))
                    meta["retrieval_count"] = str(current + increment)
                    meta["updated_at"] = updated_at_val
                    updated += 1
            self.rowcount = updated
            self._description = None
            self._rows = []
            return

        # Single row: WHERE id = %s (id always last param)
        doc_id = params[-1]
        row = self.db.rows.get(doc_id)

        if not row:
            self.rowcount = 0
            if has_returning:
                self._description = [_Col("id"), _Col("document"), _Col("metadata")]
            else:
                self._description = None
            self._rows = []
            return

        meta = row["metadata"]

        if "retrieval_count" in sql:
            # Two variants:
            # a) Hardcoded '+ 1': params = (updated_at, doc_id)
            # b) Parameterized '+ %s': params = (increment, updated_at, doc_id)
            if "+ %s)" in sql:
                increment = float(params[0])
                updated_at_val = params[1] if len(params) > 2 else None
            else:
                increment = 1.0
                updated_at_val = params[0] if len(params) > 1 else None
            current = float(meta.get("retrieval_count", 0))
            meta["retrieval_count"] = str(current + increment)
            if updated_at_val:
                meta["updated_at"] = updated_at_val
        elif "jsonb_build_object" in sql:
            if "superseded" in sql.lower():
                meta["status"] = "superseded"
                meta["superseded_by"] = params[0]
                meta["superseded_at"] = params[1]

        now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        row["updated_at"] = now
        self.rowcount = 1

        if has_returning:
            ret_match = re.search(r"RETURNING\s+(.*?)$", sql, re.I)
            cols = (
                [c.strip() for c in ret_match.group(1).split(",")]
                if ret_match
                else ["id", "document", "metadata"]
            )
            self._description = [_Col(c) for c in cols]
            self._rows = [
                tuple(
                    row["metadata"] if c == "metadata" else row.get(c)
                    for c in cols
                )
            ]
        else:
            self._description = None
            self._rows = []

    # ── DELETE handler ────────────────────────────────────────────────

    def _handle_delete(self, sql, params):
        if "metadata->>'parent_file'" in sql:
            count = self.db.delete_where_metadata("parent_file", params[0])
            self.rowcount = count
        elif "WHERE id = %s" in sql:
            deleted = self.db.delete(params[0])
            self.rowcount = 1 if deleted else 0
        else:
            self.rowcount = 0
        self._description = None
        self._rows = []

    # ── SELECT handler ────────────────────────────────────────────────

    def _handle_select(self, sql, params):
        sql_upper = sql.upper()

        # jarvis_meta queries
        if "FROM JARVIS_META" in sql_upper:
            self._handle_meta_select(sql, params)
            return

        # pg_total_relation_size
        if "PG_TOTAL_RELATION_SIZE" in sql_upper:
            self._description = [_Col("total_bytes")]
            self._rows = [(0,)]
            return

        # GROUP BY (collection_stats) — must come before COUNT(*) since
        # GROUP BY queries also contain count(*) as an aggregate column
        if "GROUP BY" in sql_upper:
            self._handle_group_by(sql, params)
            return

        # COUNT(*) — simple aggregate without GROUP BY
        if "COUNT(*)" in sql_upper:
            conditions, _ = self._extract_conditions(sql, params)
            count = self.db.count(conditions)
            alias_match = re.search(r"count\(\*\)\s+AS\s+(\w+)", sql, re.I)
            col = alias_match.group(1) if alias_match else "cnt"
            self._description = [_Col(col)]
            self._rows = [(count,)]
            return

        # Vector search (embedding <=>)
        if "embedding <=>" in sql:
            self._handle_vector_search(sql, params)
            return

        # Batch get: ANY(%s)
        if "ANY(" in sql_upper:
            ids = params[0] if params else []
            rows = self.db.get_many(ids)
            self._set_results_from_rows(sql, rows)
            return

        # Single get: WHERE id = %s
        if re.search(r"WHERE\s+id\s*=\s*%s", sql, re.I):
            row = self.db.get(params[0]) if params else None
            rows = [row] if row else []
            self._set_results_from_rows(sql, rows)
            return

        # Filtered query (metadata conditions)
        conditions, param_offset = self._extract_conditions(sql, params)
        order_by = self._extract_order_by(sql)
        limit = self._extract_limit(sql, params, param_offset)
        rows = self.db.list_filtered(conditions, order_by, limit)
        self._set_results_from_rows(sql, rows)

    def _handle_vector_search(self, sql, params):
        conditions, param_offset = self._extract_conditions(sql, params)

        # Next param is the embedding vector
        query_embedding = params[param_offset] if param_offset < len(params) else []

        # Last param is LIMIT (if present after embedding)
        limit = 10
        if len(params) > param_offset + 1:
            try:
                limit = int(params[-1])
            except (ValueError, TypeError):
                limit = 10

        results = self.db.vector_search(query_embedding, limit, conditions)

        cols = ["id", "document", "metadata", "distance"]
        self._description = [_Col(c) for c in cols]
        self._rows = [
            (r["id"], r["document"], r["metadata"], r.get("distance", 1.0))
            for r in results
        ]

    def _handle_group_by(self, sql, params):
        rows = list(self.db.rows.values())

        # Extract column aliases from SQL (e.g. metadata->>'type' AS content_type)
        def _alias(field):
            m = re.search(
                rf"metadata->>'{field}'\s+AS\s+(\w+)", sql, re.I
            )
            return m.group(1) if m else field

        if "metadata->>'type'" in sql and "metadata->>'namespace'" in sql:
            type_col = _alias("type")
            ns_col = _alias("namespace")
            groups = Counter(
                (r["metadata"].get("type", "unknown"), r["metadata"].get("namespace", ""))
                for r in rows
            )
            self._description = [_Col(type_col), _Col(ns_col), _Col("cnt")]
            self._rows = [(t, n, c) for (t, n), c in groups.most_common(20)]
        elif "metadata->>'type'" in sql:
            type_col = _alias("type")
            groups = Counter(r["metadata"].get("type", "unknown") for r in rows)
            self._description = [_Col(type_col), _Col("cnt")]
            self._rows = [(t, c) for t, c in groups.most_common(20)]
        elif "metadata->>'namespace'" in sql:
            ns_col = _alias("namespace")
            groups = Counter(r["metadata"].get("namespace", "") for r in rows)
            self._description = [_Col(ns_col), _Col("cnt")]
            self._rows = [(n, c) for n, c in groups.most_common(20)]
        else:
            self._description = [_Col("key"), _Col("cnt")]
            self._rows = []

    # ── Result helpers ────────────────────────────────────────────────

    def _set_results_from_rows(self, sql, rows):
        cols = self._extract_select_columns(sql)
        if not cols:
            cols = ["id", "document", "metadata"]

        self._description = [_Col(c) for c in cols]
        self._rows = []
        for r in rows:
            vals = []
            for c in cols:
                if c == "metadata":
                    vals.append(r.get("metadata", {}))
                elif c == "parent_file":
                    vals.append(r.get("metadata", {}).get("parent_file", ""))
                else:
                    vals.append(r.get(c))
            self._rows.append(tuple(vals))

    def _extract_select_columns(self, sql):
        m = re.search(r"SELECT\s+(.*?)\s+FROM", sql, re.I | re.S)
        if not m:
            return ["id", "document", "metadata"]

        select_part = m.group(1).strip()
        if select_part == "*":
            return ["id", "document", "metadata"]

        cols = []
        for part in select_part.split(","):
            part = part.strip()
            # Handle "expr AS alias"
            alias_match = re.search(r"\bAS\s+(\w+)\s*$", part, re.I)
            if alias_match:
                cols.append(alias_match.group(1))
                continue
            # Simple column name
            clean = re.sub(r"metadata->>'(\w+)'", r"\1", part)
            clean = re.sub(r"\(.*?\)", "", clean)
            clean = re.sub(r"::\w+", "", clean)
            clean = clean.strip()
            if clean:
                cols.append(clean)

        return cols if cols else ["id", "document", "metadata"]

    # ── SQL parsing helpers ───────────────────────────────────────────

    def _extract_conditions(self, sql, params):
        """Extract metadata conditions from WHERE clause.

        Returns (conditions, consumed_param_count).
        """
        conditions = []
        param_idx = 0

        for m in re.finditer(
            r"metadata->>'(\w+)'\)?(?:::float)?\s*(=|>=|LIKE)\s*(%s|'([^']*)')",
            sql,
        ):
            key = m.group(1)
            op = m.group(2)
            if m.group(3) == "%s":
                if param_idx < len(params):
                    value = params[param_idx]
                    param_idx += 1
                else:
                    continue
            else:
                value = m.group(4)
            conditions.append((key, op, value))

        return conditions, param_idx

    def _extract_order_by(self, sql):
        # ORDER BY (metadata->>'field')::float DESC
        m = re.search(
            r"ORDER BY\s+\(?metadata->>'(\w+)'\)?(?:::float)?\s+(ASC|DESC)",
            sql,
            re.I,
        )
        if m:
            return (m.group(1), m.group(2).upper())

        # ORDER BY field ASC/DESC (but not 'distance')
        m = re.search(r"ORDER BY\s+(\w+)\s+(ASC|DESC)", sql, re.I)
        if m and m.group(1).lower() not in ("distance",):
            return (m.group(1), m.group(2).upper())

        return None

    def _extract_limit(self, sql, params, param_offset):
        if re.search(r"LIMIT\s+%s", sql, re.I):
            if param_offset < len(params):
                try:
                    return int(params[param_offset])
                except (ValueError, TypeError):
                    pass
        m = re.search(r"LIMIT\s+(\d+)", sql, re.I)
        if m:
            return int(m.group(1))
        return None


class MockConnection:
    """Mock psycopg connection backed by InMemoryDB."""

    def __init__(self, db: InMemoryDB):
        self.db = db

    def cursor(self):
        return _CursorCtx(self.db)

    def execute(self, sql, params=None):
        """For conn.execute() calls (schema DDL)."""
        cur = MockCursor(self.db)
        cur.execute(sql, params)
        return cur

    def commit(self):
        pass


class _CursorCtx:
    """Context manager wrapping MockCursor."""

    def __init__(self, db):
        self._cursor = MockCursor(db)

    def __enter__(self):
        return self._cursor

    def __exit__(self, *args):
        pass


class _ConnCtx:
    """Context manager wrapping MockConnection."""

    def __init__(self, db):
        self._conn = MockConnection(db)

    def __enter__(self):
        return self._conn

    def __exit__(self, *args):
        pass


class MockPool:
    """Mock psycopg_pool.ConnectionPool backed by InMemoryDB."""

    def __init__(self, db: InMemoryDB):
        self.db = db

    def connection(self):
        return _ConnCtx(self.db)

    def close(self):
        pass


# ── Pytest fixtures ────────────────────────────────────────────────────


@pytest.fixture
def temp_vault() -> Generator[Path, None, None]:
    """Create a temporary vault directory for testing."""
    with tempfile.TemporaryDirectory(prefix="jarvis_test_vault_") as tmpdir:
        vault_path = Path(tmpdir)
        # Create some structure
        (vault_path / "journal" / "2026" / "01").mkdir(parents=True)
        (vault_path / "notes").mkdir()
        (vault_path / "inbox").mkdir()
        # Initialize as git repo (some tests may need this)
        os.system(f"cd {vault_path} && git init -q")
        yield vault_path


@pytest.fixture
def temp_config_dir() -> Generator[Path, None, None]:
    """Create a temporary config directory."""
    with tempfile.TemporaryDirectory(prefix="jarvis_test_config_") as tmpdir:
        yield Path(tmpdir)


@pytest.fixture
def mock_config(temp_vault: Path, temp_config_dir: Path, monkeypatch):
    """Mock the config module to use temporary paths and in-memory pgvector.

    Patches:
    - Config: uses temp vault + config directory
    - Schema: _get_pool returns MockPool backed by InMemoryDB
    - Embedding: get_embedding_service returns MockEmbeddingService
    """
    import tools.config as config_module
    import jarvis_common.config as common_config_module
    import tools.schema as schema_module
    import tools.embedding as embedding_module

    # Clear all caches
    config_module._config_cache = None
    common_config_module._config_cache = None
    schema_module._pool = None
    schema_module._pool_cache_key = None
    embedding_module._service = None
    embedding_module._service_cache_key = None

    # Create shared in-memory database
    db = InMemoryDB()

    # Create a valid config
    config_file = temp_config_dir / "config.json"
    # Use temp dirs for absolute paths that default to ~/.jarvis/
    temp_memories = temp_config_dir / "memories"
    temp_memories.mkdir(exist_ok=True)
    config_data = {
        "vault_path": str(temp_vault),
        "vault_confirmed": True,
        "configured_at": "2026-02-02T12:00:00Z",
        "memory": {
            "postgres_url": "postgresql://test:test@localhost:5432/jarvis_test",
            "project_memories_path": str(temp_memories),
        },
    }
    config_file.write_text(json.dumps(config_data))

    # Monkey-patch config in BOTH modules
    def mock_get_config():
        if common_config_module._config_cache is None:
            if config_file.exists():
                common_config_module._config_cache = json.loads(config_file.read_text())
            else:
                common_config_module._config_cache = {}
        return common_config_module._config_cache

    monkeypatch.setattr(common_config_module, "get_config", mock_get_config)
    monkeypatch.setattr(config_module, "get_config", mock_get_config)

    # Patch schema._get_pool to return MockPool
    mock_pool = MockPool(db)
    monkeypatch.setattr(schema_module, "_get_pool", lambda: mock_pool)
    monkeypatch.setattr(schema_module, "_pool", mock_pool)
    monkeypatch.setattr(schema_module, "_pool_cache_key", ("test", 768))

    # Patch embedding service
    mock_emb = MockEmbeddingService(dimensions=768)
    monkeypatch.setattr(embedding_module, "get_embedding_service", lambda: mock_emb)
    monkeypatch.setattr(embedding_module, "_service", mock_emb)
    monkeypatch.setattr(
        embedding_module, "_service_cache_key", ("mock", 768, "cpu", "mock")
    )

    def _clear_cache():
        config_module._config_cache = None
        common_config_module._config_cache = None

    class ConfigHelper:
        def __init__(self):
            self.path = config_file
            self.vault_path = temp_vault
            self.db = db  # In-memory database for direct test manipulation

        def set(self, **kwargs):
            """Update config values."""
            data = json.loads(self.path.read_text()) if self.path.exists() else {}
            data.update(kwargs)
            self.path.write_text(json.dumps(data))
            _clear_cache()

        def delete_key(self, key: str):
            """Remove a key from config."""
            data = json.loads(self.path.read_text())
            data.pop(key, None)
            self.path.write_text(json.dumps(data))
            _clear_cache()

        def delete_file(self):
            """Delete the config file entirely."""
            if self.path.exists():
                self.path.unlink()
            _clear_cache()

    return ConfigHelper()


@pytest.fixture
def unconfirmed_config(mock_config):
    """Config without vault_confirmed flag."""
    mock_config.delete_key("vault_confirmed")
    return mock_config


@pytest.fixture
def no_config(mock_config):
    """No config file exists."""
    mock_config.delete_file()
    return mock_config


@pytest.fixture(autouse=True)
def cleanup_db_state():
    """Clean up database and config caches after each test."""
    yield
    import tools.config as config_module
    import jarvis_common.config as common_config_module
    import tools.schema as schema_module
    import tools.embedding as embedding_module

    config_module._config_cache = None
    common_config_module._config_cache = None
    schema_module._pool = None
    schema_module._pool_cache_key = None
    embedding_module._service = None
    embedding_module._service_cache_key = None


@pytest.fixture
def git_repo(temp_vault: Path) -> Path:
    """Vault with initialized git repo and sample commits."""
    # Git repo already initialized in temp_vault
    os.system(f'cd {temp_vault} && git config user.email "test@example.com"')
    os.system(f'cd {temp_vault} && git config user.name "Test User"')

    # Create initial commit
    test_file = temp_vault / "test.txt"
    test_file.write_text("Initial content")
    os.system(
        f'cd {temp_vault} && git add test.txt && git commit -q -m "Initial commit"'
    )
    return temp_vault


@pytest.fixture
def git_repo_with_jarvis_commits(git_repo: Path) -> Path:
    """Git repo with sample JARVIS protocol commits."""
    journal_file = git_repo / "journal" / "2026" / "01" / "20260123153045-test-entry.md"
    journal_file.write_text("# Test Entry\n\nTest content")

    os.system(f"cd {git_repo} && git add {journal_file}")
    commit_msg = "Jarvis CREATE: Test journal entry\n\n[JARVIS:Cc:20260123153045]"
    os.system(f'cd {git_repo} && git commit -q -m "{commit_msg}"')

    note_file = git_repo / "notes" / "test-note.md"
    note_file.write_text("# Test Note")
    os.system(f"cd {git_repo} && git add {note_file}")
    edit_msg = "Jarvis EDIT: Update test note\n\n[JARVIS:Ea]"
    os.system(f'cd {git_repo} && git commit -q -m "{edit_msg}"')

    return git_repo


@pytest.fixture
def mock_subprocess(monkeypatch):
    """Mock subprocess.run for testing command failures."""
    import subprocess
    from unittest.mock import Mock

    class SubprocessMock:
        def __init__(self):
            self.call_count = 0
            self.mock_return = None
            self.mock_side_effect = None

        def set_return(self, returncode=0, stdout="", stderr=""):
            result = Mock()
            result.returncode = returncode
            result.stdout = stdout
            result.stderr = stderr
            self.mock_return = result

        def set_side_effect(self, side_effect):
            self.mock_side_effect = side_effect

        def __call__(self, *args, **kwargs):
            self.call_count += 1
            if self.mock_side_effect:
                if isinstance(self.mock_side_effect, Exception):
                    raise self.mock_side_effect
                return self.mock_side_effect(*args, **kwargs)
            return (
                self.mock_return
                if self.mock_return
                else Mock(returncode=0, stdout="", stderr="")
            )

    mock = SubprocessMock()
    monkeypatch.setattr(subprocess, "run", mock)
    return mock
